name: Upload Files from Branches

on:
  push:
    branches:
      - main
      - adf_publish

jobs:
  upload-artifact-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Upload Files from Main Branch
        uses: actions/upload-artifact@v3
        with:
          name: main-branch-artifact
          path: |
            TriggerRestarter.ps1

  upload-artifact-adf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ADF Publish Branch
        uses: actions/checkout@v2
        with:
          ref: adf_publish

      - name: Print
        run: ls

      - name: Upload Files from ADF Publish Branch
        uses: actions/upload-artifact@v3
        with:
          name: adf-publish-branch-artifact
          path: |
            adf-dev-pep/ARMTemplateParametersForFactory.json
            adf-dev-pep/ARMTemplateForFactory.json

  ARM-Template-Deployment:
    runs-on: ubuntu-latest
    needs: [upload-artifact-main, upload-artifact-adf]
    steps:
      - name: Download Files from Main Branch Artifact
        uses: actions/download-artifact@v3
        with:
          name: main-branch-artifact
          path: ./artifacts/main

      - name: Download Files from ADF Publish Branch Artifact
        uses: actions/download-artifact@v3
        with:
          name: adf-publish-branch-artifact
          path: ./artifacts/ARM

      - name: Login via Az module
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
          
      # - name: Run Azure PowerShell inline script for STOP TRIGGER
      #   uses: azure/powershell@v2
      #   with:
      #     inlineScript: ./artifacts/main/TriggerRestarter.ps1 -armTemplate ./artifacts/ARM/ARMTemplateForFactory.json -ResourceGroupName $RESOURCEGROUPNAME -DataFactoryName $DATAFACTORYNAME -predeployment $true -deleteDeployment $false
      #     azPSVersion: "latest"

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v2
        with:
          azure-resource-manager-connection: 'Visual Studio Enterprise Subscription – MPN (Chayut) (f6b0ae60-ffe3-4cec-b4e5-1e280653d722)'  # Use connection name if applicable
          subscription-id: 'f6b0ae60-ffe3-4cec-b4e5-1e280653d722'
          resource-group-name: 'adf-training'
          location: 'Southeast Asia'
          template: './artifacts/ARM/ARMTemplateForFactory.json'  # Adjust the path as necessary 
          parameters: './artifacts/ARM/ARMTemplateParametersForFactory.json'  # Adjust the path as necessary
          override-parameters: |
            -factoryName "adf-dev-pep" 
            -AzureDataLakeStorage1_properties_typeProperties_url "https://stadevpep.dfs.core.windows.net" 
            -KeyVault_properties_typeProperties_baseUrl "https://kv-dev-pb.vault.azure.net/" 
            -mpep-sta_properties_privateLinkResourceId "/subscriptions/6a469d78-5b75-453f-80c4-fdef2c1bd871/resourceGroups/rg-GH-Action-CICD/providers/Microsoft.Storage/storageAccounts/stadevpep" 
            -mpep-sta_properties_groupId "dfs" 
            -mpep-sta_properties_fqdns ["stadevpep.dfs.core.windows.net"]
            -default_properties_Environment_value "dev_" 
          add-spn-to-environment: true  # This parameter is optional; adjust based on your needs

      # - name: Run Azure PowerShell inline script for START TRIGGER
      #   uses: azure/powershell@v2
      #   with:
      #     inlineScript: ./artifacts/main/TriggerRestarter.ps1 -armTemplate ./artifacts/ARM/ARMTemplateForFactory.json -ResourceGroupName $RESOURCEGROUPNAME -DataFactoryName $DATAFACTORYNAME -predeployment $false -deleteDeployment $true
      #     azPSVersion: "latest"

