name: Upload Files from Branches

on:
  push:
    branches:
      - main
      - adf_publish

jobs:
  upload-artifact-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Upload Files from Main Branch
        uses: actions/upload-artifact@v3
        with:
          name: main-branch-artifact
          path: |
            TriggerRestarter.ps1

  upload-artifact-adf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ADF Publish Branch
        uses: actions/checkout@v2
        with:
          ref: adf_publish

      - name: Print
        run: ls

      - name: Upload Files from ADF Publish Branch
        uses: actions/upload-artifact@v3
        with:
          name: adf-publish-branch-artifact
          path: |
            adf-dev-pep/ARMTemplateParametersForFactory.json
            adf-dev-pep/ARMTemplateForFactory.json

  download-and-use-artifacts:
    runs-on: ubuntu-latest
    needs: [upload-artifact-main, upload-artifact-adf]
    steps:
      - name: Download Files from Main Branch Artifact
        uses: actions/download-artifact@v3
        with:
          name: main-branch-artifact
          path: ./artifacts/main-branch-artifact

      - name: Download Files from ADF Publish Branch Artifact
        uses: actions/download-artifact@v3
        with:
          name: adf-publish-branch-artifact
          path: ./artifacts/adf-publish-branch-artifact

      - name: List Downloaded Files
        run: |
          echo "Files from main branch:"
          ls -la ./artifacts/main
          echo "Files from adf_publish branch:"
          ls -la ./artifacts/adf
