name: Upload Files from Branches

on:
  push:
    branches:
      - main
      - adf_publish

jobs:
  upload-artifact-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Upload Files from Main Branch
        uses: actions/upload-artifact@v3
        with:
          name: main-branch-artifact
          path: |
            TriggerRestarter.ps1

  upload-artifact-adf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ADF Publish Branch
        uses: actions/checkout@v2
        with:
          ref: adf_publish

      - name: Upload Files from ADF Publish Branch
        uses: actions/upload-artifact@v3
        with:
          name: adf-publish-branch-artifact
          path: |
            adf-pep/ARMTemplateParametersForFactory.json
            adf-pep/ARMTemplateForFactory.json
