name: Upload Files from Branches

on:
  push:
    branches:
      - adf_publish

jobs:
  upload-artifact-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Upload Files from Main Branch
        uses: actions/upload-artifact@v3
        with:
          name: main-branch-artifact
          path: |
            TriggerRestarter.ps1

  upload-artifact-adf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ADF Publish Branch
        uses: actions/checkout@v2
        with:
          ref: adf_publish

      - name: Print
        run: ls

      - name: Upload Files from ADF Publish Branch
        uses: actions/upload-artifact@v3
        with:
          name: adf-publish-branch-artifact
          path: |
            adf-dev-pep/ARMTemplateParametersForFactory.json
            adf-dev-pep/ARMTemplateForFactory.json

  ARM-Template-Deployment:
    runs-on: ubuntu-latest
    needs: [upload-artifact-main, upload-artifact-adf]
    steps:
      - name: Download Files from Main Branch Artifact
        uses: actions/download-artifact@v3
        with:
          name: main-branch-artifact
          path: ./artifacts/main

      - name: Download Files from ADF Publish Branch Artifact
        uses: actions/download-artifact@v3
        with:
          name: adf-publish-branch-artifact
          path: ./artifacts/ARM

      - name: Login via Az module
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 
      
      - name: Run Azure PowerShell inline script for STOP TRIGGER
        uses: azure/powershell@v2
        with:
          inlineScript: ./artifacts/main/TriggerRestarter.ps1 
            -armTemplate ./artifacts/ARM/ARMTemplateForFactory.json 
            -ResourceGroupName ${{ vars.RESOURCEGROUPNAME }}
            -DataFactoryName ${{ vars.DATAFACTORYNAME_PROD }}
            -predeployment $true 
            -deleteDeployment $false
          azPSVersion: "latest"

      - name: Gathering keys from Azure key vault
        uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: 'kv-dev-pb'
          secrets: 'prod-sta-key, sc-sql-test'
        id: GetSecrets

      - name: 'ARM Template deployment: Resource Group scope'
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ vars.RESOURCEGROUPNAME }}
          template: ./artifacts/ARM/ARMTemplateForFactory.json
          parameters: ./artifacts/ARM/ARMTemplateParametersForFactory.json 
            factoryName=${{ vars.DATAFACTORYNAME_PROD }}
            sta_accountKey=${{ steps.GetSecrets.outputs.prod-sta-key }}
            KeyVault_properties_typeProperties_baseUrl=https://kv-dev-pb.vault.azure.net/
            sql_cv_sck_properties_typeProperties_connectionString_secretName=sc-sql-test
            sta_properties_typeProperties_url=https://staprodpep.dfs.core.windows.net/
            mpep-sta_properties_privateLinkResourceId=/subscriptions/6a469d78-5b75-453f-80c4-fdef2c1bd871/resourceGroups/rg-GH-Action-CICD/providers/Microsoft.Storage/storageAccounts/staprodpep
            mpep-sta_properties_groupId=dfs
            mpep-sta_properties_fqdns="[\"staprodpep.dfs.core.windows.net\"]"
            default_properties_Environment_value=" "
            sql_cv_sck_properties_typeProperties_connectionString_secretName=sc-sql-test

      - name: Run Azure PowerShell inline script for START TRIGGER
        uses: azure/powershell@v2
        with:
          inlineScript: ./artifacts/main/TriggerRestarter.ps1 
            -armTemplate ./artifacts/ARM/ARMTemplateForFactory.json 
            -ResourceGroupName rg-GH-Action-CICD
            -DataFactoryName adf-prod-pep 
            -predeployment $false 
            -deleteDeployment $true          
          azPSVersion: "latest"

