name: List All Files in Main and ADF Publish Branches

on:
  push:
    branches:
      - main
      - adf_publish

jobs:
  checkout-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: List All Files in Main Branch
        run: |
          echo "Files in main branch:"
          ls -R

      - name: Checkout ADF Publish Branch
        uses: actions/checkout@v2
        with:
          ref: adf_publish

      - name: List All Files in ADF Publish Branch
        run: |
          echo "Files in adf_publish branch:"
          ls -R
