name: Download and Use Artifacts

on:
  workflow_run:
    workflows: ["Upload Files from Branches"]
    types:
      - completed

jobs:
  download-and-use-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Download Files from Main Branch Artifact
        uses: actions/download-artifact@v3
        with:
          name: main-branch-artifact
          path: ./artifacts/main

      - name: Download Files from ADF Publish Branch Artifact
        uses: actions/download-artifact@v3
        with:
          name: adf-publish-branch-artifact
          path: ./artifacts/adf

      - name: List Downloaded Files
        run: |
          echo "Files from main branch:"
          ls -la ./artifacts/main
          echo "Files from adf_publish branch:"
          ls -la ./artifacts/adf
