name: List All Files

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - adf_publish

jobs:
  checkout-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2

      - name: List All Files
        run: |
          echo "Files:"
          ls -R
